### ISSUE TITLE
Driver failed to install

### ISSUE THREAD

**Issue by anandjodawat** [rotassator/omnipay-payway-restapi#11]
Can you please help me to install the driver for payway? I am using latest laravel v8,40 on local xampp server

"require": {
        "php": "^7.3|^8.0",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.3",
        "laravel/framework": "^8.40",
        "laravel/tinker": "^2.5",
        "league/omnipay": "^3.1",
        "omnipay/common": "^3.0"
    },
these packages installed successfully. but the issue with omnipay-payway 

I am attaching screenshot from my command line-

![westpac-payway](https://user-images.githubusercontent.com/31274162/119328262-8ad67880-bca1-11eb-96f5-df16ce0829b6.png)

**Comment by rotassator** [comment]
Hi @anandjodawat .

This package has a dependency on v2 of `omnipay/common`
```
"require": {
    "omnipay/common": "~2.0"
},
```
but your require block is trying to use v3 of `omnipay/common`. 

Have you tried changing your require block to match?

**Comment by anandjodawat** [comment]
thanks i resolved this sorry for late reply
