### ISSUE TITLE
Example Usage of omnipay-payway-restapi

### ISSUE THREAD

**Issue by ArjunKishore** [rotassator/omnipay-payway-restapi#2]
@rotassator Can you add some sample usage of your package please ?
Such as 
create and maintain customers
generate single-use tokens
take payments using tokenised credit card

It will be very helpful for someone new like me

**Comment by brucealdridge** [comment]
try this ... 
```php
/* @var \Omnipay\PaywayRest\Gateway $gateway */
$gateway = Omnipay::create('PaywayRest');
$gateway->setApiKeySecret($secretKey);
$message = $gateway->createCustomer([
    'customerNumber' => $customer_id,
    'singleUseTokenId' => $singleUseToken,
    'merchantId' => $merchantId,
]);
$response = $message>send();
if ($response->isSuccessful()) {
    $message = $gateway->updateCustomerContact([
        'customerNumber' => $customer_id,
        'customerName' => $first_name . ' ' . $last_name
    ]);
    $message->send();
}

**Comment by ArjunKishore** [comment]
@brucealdridge Thanks for your reply.
I am also wondering how do you get $singleUseToken everytime while you create a customer. Are there any helper function in the package that does that ?

**Comment by ArjunKishore** [comment]
@brucealdridge Thank you
